# Generated by Django 3.1.3 on 2022-11-28 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_name_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name_order',
        ),
    ]
