# Generated by Django 3.1.3 on 2022-11-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_name_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name_order',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='unknown', max_length=200),
        ),
    ]
